### ISSUE TITLE
file_rec produces duplicate results

### ISSUE THREAD

**Issue by anxolerd** [Shougo/denite.nvim#367]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
On large projects like rust, calling `:Denite file_rec` runs very slow and produces duplicate results.

## Expected
`:Denite file_rec` does not produce duplicate results

## Environment Information (Required!)

 * denite version(SHA1): 966090019a30f7fbe7ce6bd3476c0beb7e8c61c5

 * OS: Fedora 26

 * Vim/neovim version: nvim v0.2.0

 * `:CheckHealth` result(neovim only):
```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/home/oleksandr/.pyenv/versions/neovim-2/bin/python"
  - INFO: Executable: /home/oleksandr/.pyenv/versions/neovim-2/bin/python
  - INFO: Python2 version: 2.7.13
  - INFO: python-neovim version: 0.1.13
  - SUCCESS: Latest python-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/home/oleksandr/.pyenv/versions/neovim-3/bin/python"
  - INFO: Executable: /home/oleksandr/.pyenv/versions/neovim-3/bin/python
  - INFO: Python3 version: 3.6.2
  - INFO: python-neovim version: 0.1.13
  - SUCCESS: Latest python-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
" Specify a directory for plugins
call plug#begin('~/.local/share/nvim/plugged')

Plug 'Shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' }

" Initialize plugin system
call plug#end()
```

## The reproduce ways from neovim starting (Required!)

 0. Open file from big project (like https://github.com/rust-lang/rust)

 1. call `:Denite file_rec`
 2. wait for 1-2 seconds
 3. start typing

## Screen shot (if possible)
![ezgif-2-b72e7863c9](https://user-images.githubusercontent.com/6533582/30183175-260ad71c-9422-11e7-8a82-56ab84d1524b.gif)

## Upload the log file
[nvim.txt](https://github.com/Shougo/denite.nvim/files/1286031/nvim.txt)

**Comment by anxolerd** [comment]
Note: provided denite version is the one which introduces breaking changes. A previous revision does not have this bug.

**Comment by Shougo** [comment]
Fixed.

**Comment by anxolerd** [comment]
I still experience this bug. Here is a new log.

[nvim.txt](https://github.com/Shougo/denite.nvim/files/1287003/nvim.txt)
