### ISSUE TITLE
Own git-grep declaration and pattern interpreted as an option

### ISSUE THREAD

**Issue by unclechu** [Shougo/denite.nvim#415]
# Problems summary

I declared my own replacement for [grep/git from unite.vim](https://github.com/Shougo/unite.vim/blob/cc0af4798f91e1c3a4a78ae028a3ac3e61d25eb3/autoload/unite/sources/grep_git.vim#L73-L77) (look at "minimal init.vim" section) and when any pattern starts with `-` it fails because a pattern is interpreted as an option. It is related to Shougo/unite.vim#1233 but in this case here is [what we have](https://github.com/Shougo/denite.nvim/blob/1fd1217f928721255d7c671205e35a4b9e3d6d4f/rplugin/python3/denite/source/grep.py#L163-L174). I mean a separator added **after** any pattern:
```python
for pattern in context['__patterns']:
  args += self.vars['pattern_opt'] + [pattern]
args += self.vars['separator']
if context['__paths']:
  args += context['__paths']
```
But here I can't just move separator up because a *pattern* for some reason is multiple, why it is a case? How could I ever use multiple pattern value? Anyway, if I move separator above *pattern* then `pattern_opt` will be recognized as pattern or probably it will be interpreted as a pattern and rest will be interpreted as list of files (not sure about this). If pattern would be singular I could just move `separator` between `pattern_opt` and `pattern` (but it is multiple). So, any ideas how it should be fixed?

## Expected

I expect pattern such as `-smth` to be interpreted as a pattern (not an option).

## Environment Information (Required!)

 * denite version(SHA1): e0dbe66c6357b3d359388e77a982989af762e087

 * OS: Fedora 25 Workstation

 * Vim/neovim version: NVIM v0.2.3-232-g8813b29

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized build-type. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13 (outdated; from /usr/lib/python2.7/site-packages/neovim)
  - WARNING: Latest python2-neovim is NOT installed: 0.2.0

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.4
  - INFO: python3-neovim version: 0.2.0
  - OK: Latest python3-neovim is installed: 0.2.0

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
  - WARNING: Missing "neovim" gem.
    - ADVICE:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Node provider (optional)
  - INFO: Node: v8.9.1
  - WARNING: Missing "neovim" npm package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
call denite#custom#alias('source', 'grep/git', 'grep')
call denite#custom#var(
	\ 'grep/git',
	\ 'command',
	\ ['git', 'grep', '-n', '--no-color'])
call denite#custom#var('grep/git', 'default_opts', [])
call denite#custom#var('grep/git', 'recursive_opts', [])
call denite#custom#var('grep/git', 'pattern_opt', [])
call denite#custom#var('grep/git', 'separator', ['--'])
call denite#custom#var('grep/git', 'final_opts', ['.'])
```

## The reproduce ways from neovim starting (Required!)

 1. `:Denite grep/git<CR>`
 2. `Pattern: -smth<CR>`

## Screen shot (if possible)

`:messages` after attempt to use `-smth` as a pattern:
![screenshot from 2018-01-15 00-43-46](https://user-images.githubusercontent.com/799353/34919985-3c1f63bc-f98d-11e7-98d2-7d3180b780a9.png)

**Comment by Shougo** [comment]
OK.  I will fix it.

**Comment by Shougo** [comment]
> But here I can't just move separator up because a pattern for some reason is multiple, why it is a case? 

Because, grep command does support the feature using `pattern_opt`.
ag and git-grep does not support it.

**Comment by unclechu** [comment]
@Shougo I meant it's not a problem to move `pattern_opt` before separator and `pattern` after it. But my question is about is `pattern` really can be multiple?

**Comment by Shougo** [comment]
> But my question is about is pattern really can be multiple?

It can be, but it is not easy.
You need to call `denite#start()` manually.
The command line call is not supported.

**Comment by unclechu** [comment]
Okay. Maybe solution would be escaping first dash if it appears, like this: `git grep '\-smth' -- .` (not only for `git-grep`, it's just for example). Maybe you could split the logic of pattern and when it's multiple do this ecaping and when it's singular just move separator before pattern.

**Comment by unclechu** [comment]
@Shougo Maybe PR Shougo/denite.nvim#417 will work for this.

**Comment by Shougo** [comment]
I have fixed the problem.

**Comment by unclechu** [comment]
@Shougo But looking at your commit Shougo/denite.nvim@653416f I could say this issue still could be reproduced in some cases (if `pattern_opt` is set and pattern starts with `-` dash symbol).

**Comment by unclechu** [comment]
Maybe it would be better to combine it with solution from Shougo/denite.nvim@cbfd04c6f714cd7c21311bd6bf850eead94a2ba5?

**Comment by Shougo** [comment]
@unclechu Have you tested it?
I have tested it, but I cannot reproduce it.
If you can reproduce the problem, please create the miniamal init.vim.
