### ISSUE TITLE
Window layouts are not restored properly in some scenarios with :set noea

### ISSUE THREAD

**Issue by rittelle** [Shougo/denite.nvim#758]
# Problems summary

The window layout is not properly restored in some scenarios.

This seems to happen whenever the window layout contains a vertical split above a small window (see the animation). The small window needs to be smaller than the size of Denite's window. This does not happen with `:set ea` because vim resizes the splits in this case.

## Expected

The window layout should be restored to the state before Denite was opened.

## Environment Information (Required!)

 * denite version (SHA1): 27203ad

 * OS: Linux (NixOS)

 * Vim/neovim version: v0.3.8

 * `:checkhealth` or `:CheckHealth` result(neovim only):

 ```
health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - OK: General viewer should work properly!
  - WARNING: pstree is not available
    - ADVICE:
      - vimtex#view#reverse_goto is better if pstree is available.
  - OK: Compiler should work!

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/lennart/.config/nvim/init.vim
    - ADVICE:
      - :help |nvim-from-vim|

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: /nix/store/x3swj9lpp73dl17vffrnbhap2bb2ysgv-xsel-unstable-2018-01-10/bin/xsel

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/nix/store/lpl4jcphngfihf4xdsbk4sz600fh98hg-neovim-0.3.8/bin/nvim-python"
  - INFO: Executable: /nix/store/lpl4jcphngfihf4xdsbk4sz600fh98hg-neovim-0.3.8/bin/nvim-python
  - INFO: Python version: 2.7.17
  - INFO: pynvim version: 0.3.2 (outdated; from /nix/store/qflgbvi5vjbz1j47qhxf11iikd6k755x-python-2.7.17-env/lib/python2.7/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.1

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/nix/store/lpl4jcphngfihf4xdsbk4sz600fh98hg-neovim-0.3.8/bin/nvim-python3"
  - INFO: Executable: /nix/store/lpl4jcphngfihf4xdsbk4sz600fh98hg-neovim-0.3.8/bin/nvim-python3
  - INFO: Python version: 3.7.5
  - INFO: pynvim version: 0.3.2 (outdated; from /nix/store/hf99in7whr0ajbzyflkrbrlkhwmm95wc-python3-3.7.5-env/lib/python3.7/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.1

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.5p114 (2019-10-01) [x86_64-linux]
  - INFO: Host: /nix/store/lpl4jcphngfihf4xdsbk4sz600fh98hg-neovim-0.3.8/bin/nvim-ruby
  - OK: Latest "neovim" gem is installed: 0.8.0

## Node.js provider (optional)
  - INFO: Disabled. g:loaded_node_provider=1

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - OK: General viewer should work properly!
  - WARNING: pstree is not available
    - ADVICE:
      - vimtex#view#reverse_goto is better if pstree is available.
  - OK: Compiler should work!
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/tmp/2020-03-05-denite-bug/denite.nvim

set noea

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> q denite#do_map('quit')
endfunction
```

## How to reproduce problems from neovim startup (Required!)

 1. Run `:exe "normal \<C-W>s\<C-W>v\<C-W>s2\<C-W>\<Down>5\<C-W>_\<C-W>\<Up>\<C-W>s"` to create the window layout
 2. Open Denite `:Denite buffer`
 3. Close Denite `q`

The windows in the left split are not properly restored to the state before Denite was opened.

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screenshot (if possible)

[![asciicast](https://asciinema.org/a/UAHfygNacgiqw2N1ft2KY5iGA.svg)](https://asciinema.org/a/UAHfygNacgiqw2N1ft2KY5iGA)

**Comment by Shougo** [comment]
Fixed

**Comment by rittelle** [comment]
I tried it it again on the current master (cad1ca6925f8fd3c6c2bb969a5f71609c658d6c6) and the problem still persists. :/ (like in the screencast).

P.S.: Thanks for the fast response :)

**Comment by Shougo** [comment]
Really???

**Comment by Shougo** [comment]
I have tested it again, and it works for me.
Closing.

**Comment by Shougo** [comment]
> Vim/neovim version: v0.3.8

Please use the latest version of neovim.

**Comment by Shougo** [comment]
My vimrc:

```vim
set rtp+=~/work/denite.nvim
set rtp+=~/work/vim-hug-neovim-rpc
set rtp+=~/work/nvim-yarp

set noea

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> q denite#do_map('quit')
endfunction
```

If other people reproduce the problem with the latest denite + neovim, I will research it again.

**Comment by rittelle** [comment]
Updating neovim resolved the issue for me, too.
Thank you for your fast responses!

**Comment by Shougo** [comment]
OK.  It seems old neovim problem.
